# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73144fac83979659222b4d6cbfe75ba26ca9ac00225f93a71abd501f18303989b441ae76ab406aefb4467400578f7826a9cc712cf5796ca0f4feeeba5ff3e1d3

test:
  secret_key_base: 70afcf11a24d9a01132a2b74d4010594f86348dcb45a0207d40eefa6a65551f422fd511e81643abe56ce6f0660371138eaafdd6d0d529e21b483298a33b89780

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
